version: "3.12"
name: "gestor-contabil-api"

services:
  api:
    container_name: "gestor-contabil-api-api"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices: !reset [ ]
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    container_name: "gestor-contabil-api-db"
    image: postgres:16.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: