version: "3.9"
name: "gestor-contabil"

services:
  api:
    container_name: "gestor-contabil-api"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/project
    depends_on:
      - db
  db:
    container_name: "gestor-contabil-api-db"
    image: postgres:16.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5434
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: